---      
apiVersion: v1
kind: Service
metadata:
  name: einnovator-sample-superheros
spec:
  type: NodePort
  ports:
  - port: 5051
    name: http
    targetPort: 5051
    nodePort: 32155
  selector:
    app: einnovator-sample-superheros
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: einnovator-sample-superheros
spec:
  selector:
    matchLabels:
      app: einnovator-sample-superheros
  replicas: 1
  template:
    metadata:
      labels:
        app: einnovator-sample-superheros
    spec:
      containers:
      - image: einnovator/einnovator-sample-superheros
        name: einnovator-sample-superheros
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://10.245.219.65/superheros?autoReconnect=true&autoReconnectForPools=true&maxReconnects=1000&useSSL=false"
        ports:
        - containerPort: 5051
          name: http
