app:
  id: superheros
  name: Superheros
  info: "Superheros Sample App"
  
server:
  port: 5051
      
#superheros:
      
spring:
  datasource:
    url: "jdbc:hsqldb:file:/data/hsqldb/superheros"
    name: superheros
    username: ""
    password: ""
    driver-class-name: ""
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    #show-sql: true
    hibernate:
      ddl-auto : update
  servlet: #boot2
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    contentnegotiation:
      favor-path-extension: false
  banner:
    location : classpath:banner-superheros.txt
  rabbitmq:
    host: rabbitmq.sandbox.nativex.cloud
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh
    
                
banner: #boot1
    location : classpath:banner-superheros.txt
    #text: superheros
    #renderer: http://patorjk.com/software/taag/#p=display&f=Big&t=superheros

sso:
  server : https://sso.einnovator.org
  client-id: application
  client-secret: application$123
  ignoreInclude: >
    /, /superhero, /superhero/**, /api/superhero, /api/superhero/**
  registration:
    auto: true
    roles:
    - name: "SUPERHERO_MANAGER"
      display-name: "Superhero Manager"
      type: GLOBAL
      description: "User with this role can manage Superheros" 

notifications:
  server: https://****
  amqp:
    notifications-queue: superheros
  templates:
    #uri: "http://cdn.mydomain.nativex.cloud/templates/devops"  
    app: "notifications/app"
    sms: notifications/sms
    mail: notifications/mail
  registration:
    auto: true
    templates:
      - name: "Superheros Invitation"
        subject: "You received an invitation by ${principal.displayName} to join the Superhero Fan Community!"    
        medium: EMAIL
        category: SYSTEM
        uri: "invitation.html"
    types:
    - source-type: Superhero
      action-type: Create
      description: "Receive notification when a Superhero is created ?"
      category: Superhero
      mail-template:
        name: "Superhero Created"
        subject: "Superhero was created by ${principal.displayName}"
        uri: superhero.html
    - source-type: Superhero
      action-type: Update
      description: "Receive notification when a Superhero is updated ?"
      category: Superhero
      mail-template:
        name: "Superhero Updated"
        subject: "Superhero was updated by ${principal.displayName}"
        uri: superhero.html
    - source-type: Superhero
      action-type: Delete
      description: "Receive notification when a Superhero is deleted ?"
      category: Superhero
      mail-template:
        name: "Superhero Deleted"
        subject: "Superhero was deleted by ${principal.displayName}"
        uri: superhero.html



documents:
  server: https://****
  files:
    root: /.superheros/
  
social:
  server: https://****
  registration:
    auto: true
    channels:
    - name: "Superheros"
      type: "FORUM"
      purpose: "Superheros Community discussion forum"
  
ui:
  links:
    cdn: https://cdn.einnovator.org
    sso: https://sso.einnovator.org
    notifications: https://notifications.einnovator.org

---

spring:
  profiles: sandbox

sso:
  server : https://sso.samples.sandbox.nativex.cloud
  client-id: application
  client-secret: application$123
    
documents:
  server: https://documents.samples.sandbox.nativex.cloud
  
social:
  server: https://social.samples.sandbox.nativex.cloud
  
ui:
  links:
    cdn: https://cdn.samples.sandbox.nativex.cloud
    sso: https://sso.samples.sandbox.nativex.cloud
    notifications: https://notifications.samples.sandbox.nativex.cloud
  

---

spring:
  profiles: monitor
  datasource:
    url: "jdbc:mysql://localhost/superheros?verifyServerCertificate=false&useSSL=true&reconnect=true"
    password: jsimao
  rabbitmq:
    host : "localhost"
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh

sso:
  server : http://localhost:2001
  client-id: application
  client-secret: application$123

notifications:
  server: http://localhost:2011

documents:
  server: http://localhost:2021
  
social:
  server: http://localhost:2051
  
ui:
  links:
    cdn: http://localhost:1900
    sso: http://localhost:2000
    notifications: http://localhost:2010

---

spring:
  profiles: ei

sso:
  server : https://sso.einnovator.org
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.einnovator.org

documents:
  server: https://documents.einnovator.org
  
social:
  server: https://social.einnovator.org
  
ui:
  links:
    cdn: https://cdn.einnovator.org
    sso: https://sso.einnovator.org
    notifications: http://notification.einnovator.org

---

spring:
  profiles: mysandbox
 
sso:
  server : https://sso.mydomain.sandbox.nativex.cloud
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.mydomain.sandbox.nativex.cloud

documents:
  server: https://documents.mydomain.sandbox.nativex.cloud
  
social:
  server: https://social.mydomain.sandbox.nativex.cloud
  
ui:
  links:
    cdn: https://cdn.mydomain.sandbox.nativex.cloud
    sso: https://sso.mydomain.sandbox.nativex.cloud
    notifications: https://notification.mydomain.sandbox.nativex.cloud

---

spring:
  profiles: mysandbox2
 
sso:
  server : https://sso.mydomain.sandbox.nativex.cloud
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.mydomain.sandbox.nativex.cloud

documents:
  server: https://documents.mydomain.sandbox.nativex.cloud
  
social:
  server: https://social.mydomain.sandbox.nativex.cloud
  
ui:
  links:
    cdn: https://cdn.mydomain.sandbox.nativex.cloud
    sso: https://sso.mydomain.sandbox.nativex.cloud
    notifications: https://notification.mydomain.sandbox.nativex.cloud

---

spring:
  profiles: mydomain
 
sso:
  server : https://sso.mydomain.nativex.cloud
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.mydomain.nativex.cloud

documents:
  server: https://documents.mydomain.nativex.cloud
  
social:
  server: https://social.mydomain.nativex.cloud
  
ui:
  links:
    cdn: https://cdn.mydomain.nativex.cloud
    sso: https://sso.mydomain.nativex.cloud
    notifications: https://notification.mydomain.nativex.cloud


---

spring:
  profiles: mydomain2
 
sso:
  server : https://sso.mydomain.einnovator.cloud
  client-id: application
  client-secret: application$123

notifications:
  server: https://notifications.mydomain.einnovator.cloud

documents:
  server: https://documents.mydomain.einnovator.cloud
  
social:
  server: https://social.mydomain.einnovator.cloud
  
ui:
  links:
    cdn: https://cdn.mydomain.einnovator.cloud
    sso: https://sso.mydomain.einnovator.cloud
    notifications: https://notification.mydomain.einnovator.cloud

---

spring:
  profiles: mysql
  datasource:
    #url: "jdbc:mysql://*****/superheros?verifyServerCertificate=false&useSSL=true&reconnect=true"
    name: superheros
    username: "root"
    password: ""
    driver-class-name: com.mysql.jdbc.Driver    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    
---

spring:
  profiles: local
  datasource:
    url: "jdbc:mysql://localhost/superheros?verifyServerCertificate=false&useSSL=true&reconnect=true"
    password: jsimao
  rabbitmq:
    host : "localhost"
    port : 5672
    username : app
    password : "app123!"
    virtualHost: vh

sso:
  server : http://localhost:2000
  client-id: application
  client-secret: application$123

notifications:
  server: http://localhost:2010

documents:
  server: http://localhost:2020
  
social:
  server: http://localhost:2050
  
ui:
  links:
    cdn: http://localhost:1900
    sso: http://localhost:2000
    notifications: http://localhost:2010

    